### ISSUE TITLE
DateRangePicker.clear() throws NPE

### ISSUE THREAD

**Issue by Dudeplayz** [xdev-software/vaadin-date-range-picker#54]
The default implementation of `clear` in HasValue uses the default `getEmptyValue`, which is `null`. I am not sure what should happen if `clear` is called, but a NPE should never occur. I think it should jump back to the `defaultModel`.

```log
java.lang.NullPointerException: null
	at software.xdev.vaadin.daterange_picker.ui.DateRangePicker.tryFixInvalidModel(DateRangePicker.java:355) ~[vaadin-date-range-picker-2.0.0.jar:2.0.0]
	at software.xdev.vaadin.daterange_picker.ui.DateRangePicker.updateFromModel(DateRangePicker.java:333) ~[vaadin-date-range-picker-2.0.0.jar:2.0.0]
	at software.xdev.vaadin.daterange_picker.ui.DateRangePicker.setValue(DateRangePicker.java:501) ~[vaadin-date-range-picker-2.0.0.jar:2.0.0]
	at software.xdev.vaadin.daterange_picker.ui.DateRangePicker.setValue(DateRangePicker.java:63) ~[vaadin-date-range-picker-2.0.0.jar:2.0.0]
	at com.vaadin.flow.component.HasValue.clear(HasValue.java:179) ~[flow-server-2.4.2.jar:2.4.2]
```

**Comment by AB-xdev** [comment]
This should be fixed with https://github.com/xdev-software/vaadin-date-range-picker/commit/a2854ff3f920fc2ff55b53a53a6802433e2c1f3b

When calling ``clear()`` an ``UnsupportedOperationException`` is thrown.

**Comment by Dudeplayz** [comment]
Why not using the default model for clear?

**Comment by AB-xdev** [comment]
2 reasons:
1. Technical: 
There are constructors that use the ``defaultModel`` (maybe we should better rename it to ``initialModel``) directly - without a supplier.
Due to this the ``defaultModel`` is used directly by the component (changes are written immediately to it), which means, that even when you call ``clear()`` nothing will happen, because the object would be the same.
2. Logically: 
The ``clear()`` method shouldn't even be available, because when you clear a date (or date-range) what is its default value? 
It could be ``null`` - which is not a date - 
or a fixed LocalDate (e.g. ``LocalDate.MIN``) - which doesn't "clears" a field.
So there's a bit of a dilemma here 😐

**Comment by Dudeplayz** [comment]
That's true. I understand the problem now. I would suggest two additional ideas:
1. Allowing to pass a default value to the constructor, which is set, when `clear` is called. This would cause the problem, which default value should be used if none is supplied.
2. Store the relevant state information from the `initialModel` and recover/set these on `clear`.
